# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sync.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/sync.proto\"5\n\x0bTimeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63lient_time\x18\x02 \x01(\x01\"\'\n\tTimeReply\x12\x1a\n\x12\x61verage_difference\x18\x01 \x01(\x01\x32\x32\n\x08TimeSync\x12&\n\x08SendTime\x12\x0c.TimeRequest\x1a\n.TimeReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sync_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEREQUEST._serialized_start=20
  _TIMEREQUEST._serialized_end=73
  _TIMEREPLY._serialized_start=75
  _TIMEREPLY._serialized_end=114
  _TIMESYNC._serialized_start=116
  _TIMESYNC._serialized_end=166
# @@protoc_insertion_point(module_scope)
