# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import sync_pb2 as proto_dot_sync__pb2


class TimeSyncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTime = channel.unary_unary(
                '/TimeSync/SendTime',
                request_serializer=proto_dot_sync__pb2.TimeRequest.SerializeToString,
                response_deserializer=proto_dot_sync__pb2.TimeReply.FromString,
                )


class TimeSyncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeSyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTime,
                    request_deserializer=proto_dot_sync__pb2.TimeRequest.FromString,
                    response_serializer=proto_dot_sync__pb2.TimeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TimeSync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimeSync(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TimeSync/SendTime',
            proto_dot_sync__pb2.TimeRequest.SerializeToString,
            proto_dot_sync__pb2.TimeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
