# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agenda_pb2 as agenda__pb2


class AgendaStub(object):
    """Definição da interface do serviço (métodos que poderão ser invocados)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.adicionar = channel.unary_unary(
                '/agenda.Agenda/adicionar',
                request_serializer=agenda__pb2.Pessoa.SerializeToString,
                response_deserializer=agenda__pb2.Resposta.FromString,
                )
        self.buscar = channel.unary_unary(
                '/agenda.Agenda/buscar',
                request_serializer=agenda__pb2.Pessoa.SerializeToString,
                response_deserializer=agenda__pb2.Pessoa.FromString,
                )


class AgendaServicer(object):
    """Definição da interface do serviço (métodos que poderão ser invocados)
    """

    def adicionar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def buscar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgendaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'adicionar': grpc.unary_unary_rpc_method_handler(
                    servicer.adicionar,
                    request_deserializer=agenda__pb2.Pessoa.FromString,
                    response_serializer=agenda__pb2.Resposta.SerializeToString,
            ),
            'buscar': grpc.unary_unary_rpc_method_handler(
                    servicer.buscar,
                    request_deserializer=agenda__pb2.Pessoa.FromString,
                    response_serializer=agenda__pb2.Pessoa.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenda.Agenda', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agenda(object):
    """Definição da interface do serviço (métodos que poderão ser invocados)
    """

    @staticmethod
    def adicionar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agenda.Agenda/adicionar',
            agenda__pb2.Pessoa.SerializeToString,
            agenda__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def buscar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/agenda.Agenda/buscar',
            agenda__pb2.Pessoa.SerializeToString,
            agenda__pb2.Pessoa.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
